### PR TITLE
change memory usage to bit fields

### PR DESCRIPTION
**Pull request by Sanaloht**
char arrays for parsed cronexpr changed to uint8_t* bit fields
added tests for memory allocation

### CODE REVIEW

**Comment by staticlibs** [comment]
Hi, the PR looks good, thanks! The only unclear thing is, why `gmtime_s` changed to `gmtime` on windows?

Besides that, can you please make it pass "compile and test" commands from [here](https://github.com/staticlibs/ccronexpr#compilation-and-tests-run-examples) at least for some of the compilers? I really like to keep it "warning-free", currently cannot test the updated version with my app because of warnings.

**Comment by staticlibs** [comment]
Forgot another bit, could you please rename `TEST` macro to `CRON_TEST_MALLOC` or something like this?

**Comment by Sanaloht** [comment]
Macroname is fixed and use of the define extended.
The gmtime_s issues are partially due to c89 standard but mostly due to mingw32.
Defines now change if mingw is used. Can you test it now?

**Comment by staticlibs** [comment]
@Sanaloht Thanks for the update! Smoke tests are passing for me. Going to look deeper and merge it in a day or two.

**Comment by staticlibs** [comment]
Merged and fixed and changed some minor things. Overall bitfields are very nice to have. Thanks again for PR!

**Comment by ThomTe** [comment]
You're welcome and thanks to Niondir for helping!

**Pull request merged**
